# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ck2

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: sock——checkin
        env:
          CK_TOKEN: ${{ secrets.SOCKBOOM_CHECKIN_TOKEN }}
        run: |
          curl https://api.sockboom.click/client/checkin?token=${CK_TOKEN}
